name = "chinese-learning-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 特定配置
pages_build_output_dir = "dist"

# 環境變數範例（實際值在 Cloudflare Dashboard 中設定）
[vars]
NODE_ENV = "production"

# 生產環境設定
[env.production]
compatibility_flags = ["nodejs_compat"]

# 預覽環境設定  
[env.preview]
compatibility_flags = ["nodejs_compat"]